import importlib.machinery, importlib.util, json, pathlib, subprocess, tempfile, unittest

ROOT=pathlib.Path(__file__).resolve().parents[1]
loader=importlib.machinery.SourceFileLoader("cupertino",str(ROOT/"bin/cupertino"))
spec=importlib.util.spec_from_loader(loader.name,loader)
mod=importlib.util.module_from_spec(spec); loader.exec_module(mod)

class Profiles(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root=pathlib.Path(self.tmp.name)
        self.p=mod.Profile(self.root,ROOT,session=False)
        self.shell={"version":1,"idle":{"lock":567},"plugins":[{"id":"other.service"}],"bar":{"position":"bottom","transparent":False,"layout":{"left":[{"id":"omarchy.menu"},{"id":"omarchy.workspaces"}],"center":[{"id":"omarchy.clock","format":"HH:mm"}],"right":[{"id":"example.model-usage","refreshIntervalSec":456},{"id":"omarchy.network"}]}}}
        for file,data in {
            ".config/omarchy/shell.json":json.dumps(self.shell),
            ".config/hypr/looknfeel.lua":"-- existing personal settings\nhl.config({decoration={blur={enabled=true}}})\n",
            ".config/gtk-4.0/gtk.css":"/* existing stylesheet */\n",
            ".local/state/omarchy/current/theme.name":"inkypinky\n",
        }.items(): mod.atomic(self.p.path(file),data.encode())
        self.before={name:mod.capture(self.p.path(name)) for name in mod.FILES}

    def test_both_variants_restore_exact_files_and_absence(self):
        self.p.apply("light"); self.p.apply("dark"); self.p.restore()
        self.assertEqual(self.before,{n:mod.capture(self.p.path(n)) for n in mod.FILES})
        self.assertFalse(self.p.active())

    def test_existing_functions_and_settings_survive(self):
        self.p.apply("light")
        conf=json.loads(self.p.path(".config/omarchy/shell.json").read_text())
        self.assertEqual(conf["idle"],self.shell["idle"])
        self.assertIn({"id":"other.service"},conf["plugins"])
        right=conf["bar"]["layout"]["right"]
        self.assertIn({"id":"example.model-usage","refreshIntervalSec":456,"cupertinoAccessory":True},right)
        self.assertIn({"id":"omarchy.network"},right)
        self.assertEqual(conf["bar"]["id"],"cupertino.menubar")
        self.assertNotIn("omarchy.workspaces",[x["id"] for group in conf["bar"]["layout"].values() for x in group])

    def test_failure_rolls_back_partial_write(self):
        apply_files=self.p.apply_files
        def fail(mode,record):
            apply_files(mode,record)
            raise RuntimeError("injected compositor rejection")
        self.p.apply_files=fail
        with self.assertRaises(RuntimeError): self.p.apply("light")
        self.assertEqual(self.before,{n:mod.capture(self.p.path(n)) for n in mod.FILES})

    def test_symlink_and_mode_restored(self):
        path=self.p.path(".config/gtk-3.0/gtk.css")
        target=self.root/"custom.css"; target.write_text("/* untouched target */")
        path.parent.mkdir(parents=True,exist_ok=True); path.symlink_to(target)
        self.p.apply("dark"); self.p.restore()
        self.assertTrue(path.is_symlink()); self.assertEqual(path.resolve(),target)
        self.assertEqual(target.read_text(),"/* untouched target */")

    def test_switch_to_other_theme_preserves_its_generated_gtk4(self):
        self.p.apply("light")
        self.p.path(".config/gtk-4.0/gtk.css").write_text("/* generated by another theme */")
        self.p.restore(selected_theme="nord")
        self.assertEqual(self.p.path(".config/gtk-4.0/gtk.css").read_text(),"/* generated by another theme */")
        self.assertEqual(mod.capture(self.p.path(".config/omarchy/shell.json")),self.before[".config/omarchy/shell.json"])

    def test_concurrent_edits_are_preserved_before_restore(self):
        self.p.apply("light")
        self.p.path(".config/hypr/looknfeel.lua").write_text("-- user's new customization")
        self.p.restore()
        saved=list((self.p.state/"preserved-edits").glob("*looknfeel.lua.json"))
        self.assertEqual(len(saved),1)
        self.assertIn("data",json.loads(saved[0].read_text()))

    def test_theme_picker_entry_uses_last_normal_theme(self):
        self.p.remember_normal()
        self.p.path(".local/state/omarchy/current/theme.name").write_text("cupertino-light")
        self.p.apply("light",from_hook=True)
        self.assertEqual(self.p.active()["theme"],"inkypinky")

    def test_symlink_looknfeel_is_not_duplicated_between_variants(self):
        look=self.p.path(".config/hypr/looknfeel.lua")
        target=self.root/"look.lua"; target.write_text("-- custom linked look")
        look.unlink(); look.symlink_to(target)
        self.p.apply("light"); self.p.apply("dark")
        self.assertEqual(look.read_text().count("BEGIN CUPERTINO GLASS"),1)
        self.p.restore()
        self.assertTrue(look.is_symlink())
        self.assertEqual(target.read_text(),"-- custom linked look")

    def test_theme_picker_restores_preexisting_gtk4_stylesheet(self):
        self.p.remember_normal()
        self.p.path(".config/gtk-4.0/gtk.css").write_text("/* native hook ran before ours */")
        self.p.path(".local/state/omarchy/current/theme.name").write_text("cupertino-light")
        self.p.apply("light",from_hook=True); self.p.restore()
        self.assertEqual(mod.capture(self.p.path(".config/gtk-4.0/gtk.css")), self.before[".config/gtk-4.0/gtk.css"])

    def test_each_mode_retains_its_own_customizations(self):
        self.p.apply("light")
        look=self.p.path(".config/hypr/looknfeel.lua")
        look.write_text(look.read_text()+"-- custom light-only adjustment\n")
        light=look.read_bytes()
        self.p.apply("dark")
        self.assertNotIn("light-only",look.read_text())
        look.write_text(look.read_text()+"-- custom dark-only adjustment\n")
        dark=look.read_bytes()
        self.p.apply("light"); self.assertEqual(look.read_bytes(),light)
        self.p.restore(); self.assertEqual(mod.capture(look),self.before[".config/hypr/looknfeel.lua"])
        self.p.apply("dark"); self.assertEqual(look.read_bytes(),dark)

    def test_normal_edits_are_saved_on_the_next_round_trip(self):
        self.p.apply("light"); self.p.restore()
        look=self.p.path(".config/hypr/looknfeel.lua")
        look.write_text("-- new normal preference\n")
        self.p.apply("dark"); self.p.restore()
        self.assertEqual(look.read_text(),"-- new normal preference\n")

    def test_switcher_is_added_once_and_existing_widgets_are_untouched(self):
        original=json.loads(json.dumps(self.shell))
        once=self.p.with_switch(original)
        twice=self.p.with_switch(once)
        self.assertEqual(sum(x.get("id")==mod.SWITCH for v in twice["bar"]["layout"].values() for x in v),1)
        self.assertEqual(twice["bar"]["layout"]["center"],self.shell["bar"]["layout"]["center"])
        self.assertEqual(twice["idle"],self.shell["idle"])

    def test_terminal_upgrade_captures_baseline_before_stashing_old_profile(self):
        self.p.apply("light")
        record=self.p.active()
        for name in mod.TERMINAL_FILES.values():
            record["files"].pop(name); record["written"].pop(name)
            record["file_text"].pop(name)
        self.p.save(self.p.record_path,record)
        path=self.p.path(mod.TERMINAL_FILES["foot"])
        original="[main]\nfont=Monospace:size=12\n[key-bindings]\nclipboard-copy=Control+c\n"
        path.write_text(original)
        self.p.apply("light")
        self.assertIn("DejaVu Sans Mono",path.read_text())
        self.assertIn("clipboard-copy=Control+c",path.read_text())
        self.p.restore()
        self.assertEqual(path.read_text(),original)

    def test_terminal_profile_customization_and_link_are_restored(self):
        path=self.p.path(mod.TERMINAL_FILES["foot"])
        path.parent.mkdir(parents=True,exist_ok=True)
        target=self.root/"foot-shared.ini"; original="[main]\nfont=Monospace:size=12\n"
        target.write_text(original); path.symlink_to(target)
        self.p.apply("light")
        customized=path.read_text().replace("pad = 8x6","pad = 10x8")
        path.write_text(customized)
        self.p.apply("dark"); self.p.apply("light")
        self.assertEqual(path.read_text(),customized)
        self.p.restore()
        self.assertTrue(path.is_symlink())
        self.assertEqual(target.read_text(),original)

    def test_obsidian_controls_preserve_snippets_modes_and_original_symlink(self):
        vault=self.root/"Documents/My Vault"
        appearance=vault/".obsidian/appearance.json"
        original=b'{"enabledCssSnippets":["personal"],"accentColor":"#112233"}\n'
        mod.atomic(appearance,original,0o600)
        registry=self.p.path(".config/obsidian/obsidian.json")
        mod.atomic(registry,json.dumps({"vaults":{"a":{"path":str(vault)}}}).encode())
        snippet=vault/".obsidian/snippets/cupertino-window-controls.css"
        target=self.root/"personal-controls.css"; target.write_text("/* original linked controls */\n")
        snippet.parent.mkdir(); snippet.symlink_to(target)
        baseline={str(p.relative_to(self.root)):mod.capture(p) for p in (appearance,snippet)}
        self.p.apply("light")
        config=json.loads(appearance.read_text())
        self.assertEqual(config["enabledCssSnippets"],["personal","cupertino-window-controls"])
        self.assertEqual(config["accentColor"],"#112233")
        self.assertIn(".mod-close",snippet.read_text())
        customized=snippet.read_text()+"\n/* user's light-only spacing */\n"
        snippet.write_text(customized)
        self.p.apply("dark")
        self.assertNotIn("light-only",snippet.read_text())
        self.p.apply("light"); self.assertEqual(snippet.read_text(),customized)
        self.p.restore()
        self.assertEqual(baseline,{n:mod.capture(self.p.path(n)) for n in baseline})
        self.assertEqual(target.read_text(),"/* original linked controls */\n")

    def test_obsidian_new_vault_upgrade_is_restored_after_registry_removal(self):
        self.p.apply("light")
        vault=self.root/"Documents/New Vault"; (vault/".obsidian").mkdir(parents=True)
        registry=self.p.path(".config/obsidian/obsidian.json")
        mod.atomic(registry,json.dumps({"vaults":{"a":{"path":str(vault)}}}).encode())
        self.p.apply("light")
        appearance=vault/".obsidian/appearance.json"
        snippet=vault/".obsidian/snippets/cupertino-window-controls.css"
        self.assertEqual(json.loads(appearance.read_text())["enabledCssSnippets"],["cupertino-window-controls"])
        self.assertTrue(snippet.is_file())
        # Closing/removing the vault must not leave enabled styles behind.
        registry.write_text('{"vaults":{}}')
        self.p.apply("dark"); self.p.restore()
        self.assertFalse(appearance.exists()); self.assertFalse(snippet.exists())
        # A later activation must not resurrect files from an old saved mode.
        self.p.apply("light"); self.p.restore()
        self.assertFalse(appearance.exists()); self.assertFalse(snippet.exists())

    def chatgpt_ready(self):
        launch=self.p.install_root/"adapters/chatgpt/launch"
        # An inert selector records arguments. No real application is launched.
        mod.atomic(launch,b'#!/usr/bin/env python3\nimport json,sys\nprint(json.dumps(sys.argv[1:]))\n',0o755)
        application=self.p.install_root/"apps/chatgpt/26.928.21956-stable-controls"
        mod.atomic(application/"ChatGPT",b'#!/bin/sh\nexit 0\n',0o755)
        mod.atomic(application/"cupertino-adapter.json",b'{"version":"26.928.21956"}\n')
        return launch,application

    def test_chatgpt_without_prepared_copy_leaves_launchers_unmanaged(self):
        desktop=self.p.path(mod.CHATGPT_DESKTOP)
        cli=self.p.path(".local/bin/chatgpt")
        mod.atomic(desktop,b'[Desktop Entry]\nExec=/usr/bin/chatgpt --ozone-platform=wayland %U\n',0o640)
        mod.atomic(cli,b'#!/bin/sh\nexec /usr/bin/chatgpt --personal "$@"\n',0o750)
        before={name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES}
        # A selector alone is not a complete runtime and must not opt in.
        mod.atomic(self.p.install_root/"adapters/chatgpt/launch",b'#!/bin/sh\nexit 0\n',0o755)
        self.p.apply("light")
        self.assertFalse(set(mod.CHATGPT_FILES)&self.p.active()["files"].keys())
        self.assertEqual(before,{name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES})
        self.p.apply("dark"); self.p.restore()
        self.assertEqual(before,{name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES})

    def test_chatgpt_cli_arguments_desktop_fields_modes_and_original_absence(self):
        launch,_=self.chatgpt_ready()
        desktop=self.p.path(mod.CHATGPT_DESKTOP);cli=self.p.path(".local/bin/chatgpt")
        original=(b'[Desktop Entry]\r\nName=My ChatGPT\r\nExec=/usr/bin/chatgpt --ozone-platform=wayland %U\r\n'
                  b'TryExec=/usr/bin/chatgpt\r\nIcon=personal-icon\r\nMimeType=x-scheme-handler/codex;\r\n'
                  b'[Desktop Action New]\r\nExec="/usr/bin/chatgpt" --new-window\r\n')
        mod.atomic(desktop,original,0o640)
        self.p.apply("light")
        rewritten=original.replace(b'Exec=/usr/bin/chatgpt ',b'Exec="'+str(launch).encode()+b'" ')
        rewritten=rewritten.replace(b'Exec="/usr/bin/chatgpt" ',b'Exec="'+str(launch).encode()+b'" ')
        self.assertEqual(desktop.read_bytes(),rewritten)
        self.assertEqual(desktop.stat().st_mode&0o777,0o640)
        self.assertEqual(cli.stat().st_mode&0o777,0o755)
        args=['codex://a/b','a path with spaces','--literal=$(do-not-run)','quote"value']
        result=subprocess.run([str(cli),*args],capture_output=True,text=True,check=True)
        self.assertEqual(json.loads(result.stdout),args)
        light_desktop=rewritten+b'X-Personal=light\r\n';desktop.write_bytes(light_desktop)
        light_cli=cli.read_bytes()+b'# personal light arguments\n';mod.atomic(cli,light_cli,0o750)
        self.p.apply("dark")
        self.assertEqual(desktop.read_bytes(),rewritten)
        self.assertNotIn(b'personal light',cli.read_bytes())
        dark_desktop=rewritten+b'X-Personal=dark\r\n';desktop.write_bytes(dark_desktop)
        self.p.apply("light")
        self.assertEqual(desktop.read_bytes(),light_desktop)
        self.assertEqual(cli.read_bytes(),light_cli)
        self.assertEqual(cli.stat().st_mode&0o777,0o750)
        self.p.restore()
        self.assertEqual(desktop.read_bytes(),original)
        self.assertEqual(desktop.stat().st_mode&0o777,0o640)
        self.assertFalse(cli.exists())
        self.p.apply("dark");self.assertEqual(desktop.read_bytes(),dark_desktop)
        self.p.restore();self.assertEqual(desktop.read_bytes(),original)

    def test_chatgpt_original_symlinks_and_their_targets_survive(self):
        self.chatgpt_ready()
        desktop=self.p.path(mod.CHATGPT_DESKTOP);cli=self.p.path(".local/bin/chatgpt")
        desktop_target=self.root/"personal.desktop"
        desktop_bytes=b'[Desktop Entry]\nExec=/usr/bin/chatgpt %U\nName=Original\n'
        mod.atomic(desktop_target,desktop_bytes,0o640)
        cli_target=self.root/"original-launcher"
        mod.atomic(cli_target,b'#!/bin/sh\nexit 0\n',0o700)
        desktop.parent.mkdir(parents=True,exist_ok=True);desktop.symlink_to(desktop_target)
        cli.parent.mkdir(parents=True,exist_ok=True);cli.symlink_to(cli_target)
        before={name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES}
        self.p.apply("light");desktop.write_bytes(desktop.read_bytes()+b'X-Only=light\n')
        self.p.apply("dark");self.assertNotIn(b'X-Only=light',desktop.read_bytes())
        self.p.restore()
        self.assertEqual(before,{name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES})
        self.assertEqual(desktop_target.read_bytes(),desktop_bytes)
        self.assertEqual(cli_target.read_bytes(),b'#!/bin/sh\nexit 0\n')
        self.assertEqual(cli_target.stat().st_mode&0o777,0o700)

    def test_chatgpt_missing_local_desktop_is_not_fabricated(self):
        self.chatgpt_ready();self.p.apply("light")
        self.assertTrue(self.p.path(".local/bin/chatgpt").is_file())
        self.assertFalse(self.p.path(mod.CHATGPT_DESKTOP).exists())
        self.p.apply("dark");self.p.restore()
        self.assertTrue(all(mod.capture(self.p.path(n))=={"type":"absent"} for n in mod.CHATGPT_FILES))

    def test_chatgpt_removed_runtime_restores_baseline_without_reviving_saved_wrappers(self):
        launch,application=self.chatgpt_ready()
        desktop=self.p.path(mod.CHATGPT_DESKTOP);cli=self.p.path(".local/bin/chatgpt")
        original=b'[Desktop Entry]\nExec=/usr/bin/chatgpt %U\n'
        mod.atomic(desktop,original)
        self.p.apply("light")
        customized=desktop.read_bytes()+b'X-Saved=light\n';desktop.write_bytes(customized)
        self.p.apply("dark")
        dark=desktop.read_bytes()+b'X-Saved=dark\n';desktop.write_bytes(dark)
        self.p.apply("light")
        (application/"ChatGPT").unlink()
        self.p.apply("dark")
        self.assertEqual(desktop.read_bytes(),original);self.assertFalse(cli.exists())
        self.p.apply("light")
        self.assertEqual(desktop.read_bytes(),original);self.assertFalse(cli.exists())
        self.chatgpt_ready();self.p.apply("dark")
        self.assertEqual(desktop.read_bytes(),dark)
        self.p.apply("light");self.assertEqual(desktop.read_bytes(),customized)
        self.p.restore();self.assertEqual(desktop.read_bytes(),original);self.assertFalse(cli.exists())

    def test_chatgpt_upgrade_captures_an_existing_binary_cli_before_touching_it(self):
        self.p.apply("light")
        cli=self.p.path(".local/bin/chatgpt");original=b'\x7fELF\xff\x00personal binary bytes'
        mod.atomic(cli,original,0o750)
        desktop=self.p.path(mod.CHATGPT_DESKTOP)
        desktop_bytes=b'[Desktop Entry]\nExec=/usr/bin/chatgpt %U\n'
        mod.atomic(desktop,desktop_bytes)
        self.chatgpt_ready();self.p.apply("light")
        self.assertTrue(cli.read_bytes().startswith(b'#!/bin/sh\n'))
        self.p.restore();self.assertEqual(cli.read_bytes(),original)
        self.assertEqual(cli.stat().st_mode&0o777,0o750)
        self.assertEqual(desktop.read_bytes(),desktop_bytes)

    def test_chatgpt_launchers_roll_back_if_activation_fails(self):
        self.chatgpt_ready()
        desktop=self.p.path(mod.CHATGPT_DESKTOP)
        original=b'[Desktop Entry]\nExec=/usr/bin/chatgpt %U\n'
        mod.atomic(desktop,original,0o600)
        before={name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES}
        apply_files=self.p.apply_files
        def fail(mode,record):
            apply_files(mode,record)
            raise RuntimeError('after launcher installation')
        self.p.apply_files=fail
        with self.assertRaises(RuntimeError):self.p.apply("dark")
        self.assertEqual(before,{name:mod.capture(self.p.path(name)) for name in mod.CHATGPT_FILES})

    def vscode_ready(self):
        root=self.p.install_root
        mod.atomic(root/'adapters/vscode/launch',b'#!/bin/sh\nexit 0\n',0o755)
        app=root/'apps/vscode/1.139.1'
        mod.atomic(app/'bin/code',b'#!/bin/sh\nexit 0\n',0o755)
        mod.atomic(app/'cupertino-adapter.json',b'{}\n')
        return app

    def test_vscode_preserves_original_link_target_and_independent_variants(self):
        self.vscode_ready()
        target=self.root/'original-code';target.write_bytes(b'original launcher\n')
        cli=self.p.path('.local/bin/code');cli.parent.mkdir(parents=True,exist_ok=True);cli.symlink_to(target)
        self.p.apply('light');self.assertFalse(cli.is_symlink())
        with cli.open('a') as stream:stream.write('# only light\n')
        self.p.apply('dark');self.assertNotIn('only light',cli.read_text())
        self.p.apply('light');self.assertIn('only light',cli.read_text())
        self.p.restore();self.assertTrue(cli.is_symlink());self.assertEqual(cli.resolve(),target)
        self.assertEqual(target.read_bytes(),b'original launcher\n')

    def test_vscode_removed_adapter_does_not_restore_saved_wrapper(self):
        app=self.vscode_ready();cli=self.p.path('.local/bin/code')
        self.p.apply('light');self.p.apply('dark')
        (app/'cupertino-adapter.json').unlink()
        self.p.apply('light');self.assertFalse(cli.exists())
        self.p.restore();self.assertFalse(cli.exists())

if __name__=="__main__": unittest.main()
